let
    Source = Csv.Document(File.Contents("C:\Users\PC\Downloads\MW Project Master Sheet - Master Sheet (1).csv"),[Delimiter=",", Columns=59, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order Date", type text}, {"Order No", type text}, {"Path Name", type text}, {"Customer Name", type text}, {"Project ID", type text}, {"MW Contractor", type text}, {"Path Status", type text}, {"Order Status", type text}, {"Order Stage", type text}, {"Order Type", type text}, {"Stage Date", type text}, {"In Service", type text}, {"Decommissioned Date", type text}, {"District", type text}, {"Tagg", type text}, {"Current Status", type text}, {"FE Tower Owner", type text}, {"NE Tower Owner", type text}, {"Tawal Status", type text}, {"LOS Survey Date", type text}, {"LOS Survey Status", type text}, {"WNI Submit Date Date", type text}, {"WNI Status", type text}, {"WNI Received Date", type text}, {"Backhuaul Status", type text}, {"Backhaul Type", type text}, {"WGW ID", type text}, {"Port Info", type text}, {"Installation Date", type text}, {"Installation Status", type text}, {"FE Property ID", type text}, {"FE MW Dish Size", type text}, {"FE MW Dish Height", type text}, {"FE MW Dish Azimuth", type text}, {"FE Antenna Weight", type text}, {"FE Required Capacity of DC Power Source (in kW)", type text}, {"NE Property ID", type text}, {"NE MW Dish Size", type text}, {"NE MW Dish Height", type text}, {"NE MW Dish Azimuth", type text}, {"NE Antenna Weight", type text}, {"NE Required Capacity of DC Power Source (in kW)", type text}, {"TAWAL - WNI Comments", type text}, {"FE OLO Request ID", type text}, {"NE OLO Request ID", type text}, {"Tawal Feedback on link", type text}, {"Date of request", type text}, {"Date Of Feedback", type text}, {"Rejection Reason", type text}, {"MW Dsign Status", type text}, {"MW DESIGN TD", type text}, {"MW Design Link ID", type text}, {"PtMP Path", type text}, {"MW Design Remark", type text}, {"Installation Plan", type text}, {"Notes", type text}, {"CSDD Remark", type text}, {"Link is active", type text}, {"Link ID Check", type text}})
in
    #"Changed Type"